export default [
  "What's stopping you?",
  'Winter is coming.',
  "Don't burn bridges.",
  'Turn jeans inside out when washing them to help preserve their colour.',
  'Always double check you actually attached the file to the email.',
  "Your smile could make someone's day, don't forget to wear it.",
  'If you have the chance, take it!',
  'Eat food. Not too much, mostly plants.',
  "If you can't do anything about it, there's no point in worrying about it.",
  "Don't give a speech. Put on a show.",
  'State the problem in words as clearly as possible.',
  'Measure twice, cut once.',
  "Everyone has their down days. Don't take it out on innocent bystanders.",
  "If you're squashed close to strangers on public transport, try not to be rude to them. No one likes those situations.",
  'Remedy tickly coughs with a drink of honey, lemon and water as hot as you can take.',
  'Stop using the term "busy" as an excuse.',
  'A problem shared is a problem halved.',
  "Never regret. If it's good, it's wonderful. If it's bad, it's experience.",
  "Never regret. If it's good, it's wonderful. If it's bad, it's experience.",
  'Gratitude is said to be the secret to happiness.',
  'Never set an alarm clock unless you know how to switch it off',
  'Look people in the eye.',
  'When something goes wrong in life, just shout "plot twist!" and carry on.',
  'Why wait until valentines day for a romantic gesture?',
  'Taking photos with tablet devices looks weird.',
  "Don't judge a book by its cover, unless it has a synopsis on the back.",
  "If you're squashed close to strangers on public transport, try not to be rude to them. No one likes those situations.",
  "Things are just things. Don't get too attached to them.",
  'Have a firm handshake.',
  'The sun always shines above the clouds.',
  'Taking photos with tablet devices looks weird.',
  'Giving someone a hug can be mutually rewarding. Try to give at least one hug a day to someone.',
  "Don't cross the streams.",
  "If you can't do anything about it, there's no point in worrying about it.",
  'Learn to handle criticism.',
  'When painting a room, preparation is key. The actual painting should account for about 40% of the work.',
  'Turn jeans inside out when washing them to help preserve their colour.',
  "Don't promise what you can't deliver.",
  'Try making a list.',
  "Don't waste food.",
  "If you think nobody cares if you're alive, try missing a few payments.",
  'Do something selfless.',
  "If you've nothing nice to say, say nothing.",
  "Try to do the things that you're incapable of.",
  'Life is better when you sing about bananas.',
  "It always seems impossible, until it's done.",
  'Try using an old idea.',
  'Learn to handle criticism.',
  "You don't need to floss all of your teeth. Only the ones you want to keep.",
  'You have as many hours in a day as the people you admire most.',
  "It's wrong to be right.",
  'Build something out of LEGO.',
  "Don't try and bump start a motorcycle on an icy road.",
  "You don't need to floss all of your teeth. Only the ones you want to keep.",
  'Do not check work email on your days off.',
  'Some people would be better off if they took their own advice.',
  'You have as many hours in a day as the people you admire most.',
  'Put a piece of kitchen roll in with your bag of leaves to make them last longer.',
  'Happiness is a journey, not a destination.',
  'Age is of no importance, unless you are a cheese.',
  'Always the burrito.',
  'You never really grow up.',
  'Always seek out advice or opinions when making a decision.',
  "Don't eat non-snow-coloured snow.",
  'If you need cheering up, try searching online for photos of kittens.',
  'The more ideas that you give away, the more ideas that will come to you.',
  'When the cistern is filling, the seat is probably still warm.',
  "It's not about who likes you, it's about who you like.",
  'For every complex problem there is an answer that is clear, simple, and wrong.',
  'Always get two ciders.',
  "When you're looking up at birds flying overhead, keep your mouth closed.",
  'If your hair is thinning, try dying your hair a similar tone to your scalp.',
  'A common regret in life is wishing one had the courage to be ones true self.',
  'As things get closer to the light, the shadows get darker.',
  'If it still itches after a week, go to the doctors.',
  'As things get closer to the light, the shadows get darker.',
  "You don't need to floss all of your teeth. Only the ones you want to keep.",
  "You don't need to floss all of your teeth. Only the ones you want to keep.",
  'Never run with scissors.',
  'A long walk alone with some time to think, can work wonders.',
  "Don't eat anything your grandparents wouldn't recognise as food.",
  "Never regret. If it's good, it's wonderful. If it's bad, it's experience.",
  "You spend half your life asleep or in bed. It's worth spending money on a good mattress, decent pillows and a comfy duvet.",
  "Today, do not use the words â€˜Kind of,' â€˜Sort of' or â€˜Maybe.' It either is or it isn't.",
  'Good things come to those who wait.',
  'Never pay full price for a sofa at DFS.',
  'Make choices and dont look back.',
  'Do a bit more for your friends.',
  'Tell it like it is.',
  'If you cannot unscrew the lid of a jar, try placing a rubber band around its circumference for extra grip.',
  "It's wrong to be right.",
  'A common regret in life is wishing one had the courage to be ones true self.',
  'What could you increase? What could you reduce?',
  'Never cut your own fringe.',
  'You can have too much of a good thing.',
  'Vinegar is a powerful cleaning agent.',
  'Gratitude is said to be the secret to happiness.',
  'When having a clear out, ask yourself if an item has any financial, practical or sentimental value. If not, chuck it.',
  'Stop using the term "busy" as an excuse.',
  "Try to not compliment people on things they don't control.",
  "Repeat people's names when you meet them.",
  "It's unlucky to be superstitious.",
  "Don't use Excel or Powerpoint documents for your basic word processing needs.",
  'YOLO',
  "Don't use Excel or Powerpoint documents for your basic word processing needs.",
  'Most things look better when you put them in a circle.',
  'Most things look better when you put them in a circle.',
  "Don't cross the streams.",
  'When the cistern is filling, the seat is probably still warm.',
  "You don't need to floss all of your teeth. Only the ones you want to keep.",
  "It's unlucky to be superstitious.",
  "Don't take life too seriously.",
  'If you think your headphones are dying, check the socket for fluff with a straightened paperclip.',
  'Never cut your own fringe.',
  'Good advice is something a man gives when he is too old to set a bad example.',
  "One of the top five regrets people have is that they didn't have the courage to be their true self.",
  'If you are ever in doubt about whether or not to wash your hair: Wash it.',
  'Always get two ciders.',
  'The number of vampires in the average home, is directly proportional to the amount of garlic bread in the fridge.',
  'Exercise in the rain can really make you feel alive.',
  'As you get older, learn never to trust a fart.',
  "Don't be afraid to ask questions.",
  'What could you increase? What could you reduce?',
  'Respect your elders.',
  "Don't eat anything your grandparents wouldn't recognise as food.",
  'You have as many hours in a day as the people you admire most.',
  'Sing in the shower.',
  'Work is never as important as you think it is.',
  'Never buy cheap cling film.',
  "If you don't ask, you don't get.",
  'Always block trolls.',
  'Lemon and salt works wonders on tarnished brass.',
  'Brush your teeth the moment you get up.',
  'The hardest things to say are usually the most important.',
  "Don't burn bridges.",
  'You will always regret the round of Tequila.',
  "Don't judge a book by its cover, unless it has a synopsis on the back.",
  "You don't need to floss all of your teeth. Only the ones you want to keep.",
  'You have as many hours in a day as the people you admire most.',
  "Never write in an email to someone, something which you wouldn't say to that person's face.",
  'Always the burrito.',
  'Measure twice, cut once.',
  'Respect your elders.',
  "Don't be afraid to ask questions.",
  'The most important thing is the thing most easily forgotten.',
  'As things get closer to the light, the shadows get darker.',
  'A problem shared is a problem halved.',
  "Don't promise what you can't deliver.",
  'You never really grow up.',
  'Never waste an opportunity to tell someone you love them.',
  "You're not as fat as you think you are.",
  'What could you increase? What could you reduce?',
  'No "brand" is your friend.',
  'Quality beats quantity.',
  "Don't eat anything your grandparents wouldn't recognise as food.",
  'To cleanly remove the seed from an Avocado, lay a knife firmly across it, and twist.',
  'Try to pay at least one person a compliment every day.',
  "Don't promise what you can't deliver.",
  'Never set an alarm clock unless you know how to switch it off',
  'Do not seek praise, seek criticism.',
  'There is no reason at all to believe that White Wine is any different to water when it comes to removing Red Wine stains.',
  'Most things are not as bad as you think they are.',
  "Don't try and bump start a motorcycle on an icy road.",
  "When you're looking up at birds flying overhead, keep your mouth closed.",
  'A problem shared is a problem halved.',
  'A problem shared is a problem halved.',
  'The sun always shines above the clouds.',
  'Most things done in secrecy are better left undone.',
  'Identify sources of happiness.',
  "Don't waste food.",
  "When you're looking up at birds flying overhead, keep your mouth closed.",
  "Don't give a speech. Put on a show.",
  "Don't take life too seriously.",
  "Life is short enough, don't race to the finish.",
  'When faced with a choice, do both.',
  'Try buying a coffee for the creator of a free public API, now and then.',
  'Identify sources of happiness.',
  'A nod is as good as a wink to a blind horse.',
  'Learn from your mistakes.',
  'Have a firm handshake.',
  'To improve productivity, always have a shittier task to put off.',
  "Rule number 1: Try not to die. Rule number 2: Don't be a dick.",
  "When you look around and don't see anyone you respect, its time to leave.",
  "Be brave. Even if you're not, pretend to be. No one can tell the difference.",
  'For every complex problem there is an answer that is clear, simple, and wrong.',
  'Most things done in secrecy are better left undone.',
  "If you're feeling tired or anxious, a pint of water will almost always make you feel better.",
  'Vinegar is a powerful cleaning agent.',
  'Never buy cheap cling film.',
  "Don't wear clean trousers when walking your dog in the park.",
  'Never pay full price for a sofa at DFS.',
  "Don't burn bridges.",
  "Just because you are offended, doesn't mean you are right.",
  "Don't burn bridges.",
  'A nod is as good as a wink to a blind horse.',
  'If you need cheering up, try searching online for photos of kittens.',
  "It's wrong to be right.",
  'As you get older, learn never to trust a fart.',
]
