export default [
  'The HyperMart outside of Garland Texas has 58 check-outs.',
  'Stewardesses is the longest word that is typed with only the left hand.',
  'The first contraceptive was crocodile dung used by the ancient Egyptians.',
  'Most Egyptians died by the time they were 30 about 300 years ago,',
  "The scene where Indiana Jones shoots the swordsman in Raider’s of the Lost Ark was Harrison Ford's idea so that he could take a bathroom break.",
  'PEZ candy even comes in a Coffee flavor.',
  'The name of all continents in the world end with the same letter that they start with.',
  'The king of hearts is the only king without a mustache.',
  'A full-loaded supertanker traveling at normal speed takes at least 20 minutes to stop.',
  'The amount of computer Memory required to run WordPerfect for Win95 is 8 times the amount needed aboard the space shuttle.',
  'For some time Frederic Chopin, the composer and pianist, wore a beard on only one side of his face, explaining: "It does not matter, my audience sees only my right side."',
  'One third of all cancers are sun related.',
  'The Pentagon, in Arlington, Virginia, has twice as many bathrooms as is necessary, because when it was built in the 1940s, the state of Virginia still had segregation laws requiring separate toilet facilities for blacks and whites.',
  'An eighteenth-century German named Matthew Birchinger, known as "the little man of Nuremberg," played four musical instruments including the bagpipes, was an expert calligrapher, and was the most famous stage magician of his day. He performed tricks with the cup and balls that have never been explained. Yet Birchinger had no hands, legs, or thighs, and was less than 29 inches tall.',
  '100% of lottery winners do gain weight',
  '70% of all boats sold are used for fishing.',
  'A ducks quack doesnt echo, and no one knows why.',
  'Two-thirds of the worlds eggplant is grown in New Jersey.',
  'The katydid bug hears through holes in its hind legs!',
  'Studies have shown that children laugh an average of 300 times/day and adults 17 times/day, making the average child more optimistic, curious, and creative than the adult.',
  'The Earth experiences 50,000 Earth quakes per year and is hit by Lightning 100 times a second.',
  'On the ground, a group of geese is a gaggle, in the sky it is a skein.',
  'THE MOST UNUSUAL CANNONBALL: On two occasions, Miss Rita Thunderbird remained inside the cannon despite a lot of gunpowder encouragement to do otherwise. She performed in a gold lamé bikini and on one of the two occasions (1977) Miss Thunderbird remained lodged in the cannon, while her bra was shot across the Thames River.',
  'On average, people fear spiders more than they do death.',
  'In a lifetime the average human produces enough quarts of spit to fill 2 swimming pools.',
  'The placement of a donkeys eyes in its heads enables it to see all four feet at all times!',
  'The katydid bug hears through holes in its hind legs!',
  'The Great Wall of China is the only man-made structure visible from space.',
  'James Bonds car had three different license plates in Goldfinger',
  'Poland is the "stolen car capital of the world".',
  'A full-loaded supertanker traveling at normal speed takes at least 20 minutes to stop.',
  'Celery has negative calories! It takes more calories to eat a piece of celery than the celery has in it.',
  'It is illegal to eat oranges while bathing in California.',
  'Between 2 and 3 jockeys are killed each year in horse racing.',
  'The human tongue tastes bitter things with the taste buds toward the back. Salty and pungent flavors are tasted in the middle of the tongue, sweet flavors at the tip!',
  'Camels have three eyelids to protect themselves from blowing sand!',
  'In England, the Speaker of the House is not allowed to speak.',
  'Jefferson invented the dumbwaiter, the monetary system, and the folding attic ladder.',
  'There is a town in Newfoundland, Canada called Dildo.',
  'Iceland consumes more Coca-Cola per capita than any other nation.',
  'In 1778, fashionable women of Paris never went out in blustery weather without a lightning rod attached to their hats.',
  'To "testify" was based on men in the Roman court swearing to a statement made by swearing on their testicles.',
  'In space, astronauts are unable to cry, because there is no gravity and the tears wont flow.',
  'In space, astronauts are unable to cry, because there is no gravity and the tears wont flow.',
  'To Ensure Promptness, one is expected to pay beyond the value of service – hence the later abbreviation: T.I.P.',
  'Barbies full name is Barbara Millicent Roberts.',
  'A snail can sleep for three years.',
  'When a Hawaiian woman wears a flower over her left ear, it means that she is not available.',
  'The cruise liner, Queen Elizabeth II, moves only six inches for each gallon of diesel that it burns.',
  'If Texas were a country, its GNP would be the fifth largest of any country in the world.',
  '3.9% of all women do not wear underwear.',
  'Count the number of cricket chirps in a 15-second period, add 37 to the total, and your result will be very close to the actual outdoor Fahrenheit temperature.',
  'Eating the heart of a male Partridge was the cure for impotence in ancient Babylon.',
  'Shakespeare invented the word assassination and bump.',
  'Larry Lewis ran the 100-yard dash in 17.8 seconds in 1969, thereby setting a new worlds record for runners in the 100-years-or-older class. He was 101.',
  'A giraffe can go without water longer than a camel.',
  'Any free-moving liquid in outer space will form itself into a sphere, because of its surface tension.',
  '5,840 people with pillow related injuries checked into U.S. emergency rooms in 1992.',
  'One third of all cancers are sun related.',
  '111,111,111 x 111,111,111 = 12,345,678,987,654,321',
  'Poland is the "stolen car capital of the world".',
  'Peanuts actually grow underground, as opposed to nuts like walnuts, almonds, etc. that grow on trees (and are sometimes referred to as "tree nuts"). Peanuts, along with beans and peas, belong to the single plant family, Leguminosae. Legumes are edible seeds enclosed in pods.',
  'Peanuts are one of the ingredients of dynamite.',
  'Coca-Cola was originally green.',
  'In the marriage ceremony of the ancient Inca Indians of Peru, the couple was considered officially wed when they took off their sandals and handed them to each other.',
  'The world record for spitting a watermelon seed is 65 feet 4 inches.',
  'The letters KGB stand for Komitet Gosudarstvennoy Bezopasnosti.',
  'If you have three quarters, four dimes, and four pennies, you have $1.19, the largest amount of money in coins without being able to make change for a dollar.',
  'Women manage the money and pay the bills in 75% of all Americans households.',
  'The amount of computer Memory required to run WordPerfect for Win95 is 8 times the amount needed aboard the space shuttle.',
  'If a rooster cant fully extend its neck, it cant crow.',
  'Only 6 people in the whole world have died from moshing.',
  'Over 1000 birds a year die from smashing into windows!',
  'Hong Kong holds the most Rolls Royce’s per capita.',
  'In The Empire Strikes Back there is a potato hidden in the asteroid field',
  'The pop you hear when you crack your knuckles is actually a bubble of gas burning.',
  'Lorne Greene had one of his nipples bitten off by an alligator while he was host of Lorne Greenes Wild Kingdom.',
  'Its possible to lead a cow upstairs but not downstairs.',
  'The amount of computer Memory required to run WordPerfect for Win95 is 8 times the amount needed aboard the space shuttle.',
  'Two-thirds of the worlds eggplant is grown in New Jersey.',
  'The first episode of "Joanie Loves Chachi" was the highest rated American program in the history of Korean television, a country where "Chachi" translates to "penis".',
  'February 1865 is the only month in recorded history not to have a full moon.',
  'Researchers at the Texas Department of Highways in Fort Worth determined the cow population of the U.S. burps some 50 million tons of valuable hydrocarbons into the atmosphere each year. The accumulated burps of ten average cows could keep a small house adequately heated and its stove operating for a year.',
  'The Great Wall of China is the only man-made structure visible from space.',
  '3.9% of all women do not wear underwear.',
  'The first episode of "Joanie Loves Chachi" was the highest rated American program in the history of Korean television, a country where "Chachi" translates to "penis".',
  'Between 2 and 3 jockeys are killed each year in horse racing.',
  '3.6 cans of Spam are consumed each second.',
  'WWII fighter pilots in the South Pacific armed their airplanes while stationed with .50 caliber machine gun ammo belts measuring 27 feet before being loaded into the fuselage. If the pilots fired all their ammo at a target, he went through "the whole 9 yards", hence the term.',
  'One-fourth of the worlds population lives on less than $200 a year. Ninety million people survive on less than $75 a year.',
  'American Airlines saved $40,000 in 1987 by eliminating one olive from each salad served in first-class.',
  'The HyperMart outside of Garland Texas has 58 check-outs.',
  'The name Wendy was made up for the book "Peter Pan."',
  'It is illegal to eat oranges while bathing in California.',
  'A shark is the only fish that can blink with both eyes.',
  'Each month, there is at least one report of UFOs from each province of Canada.',
  'Average life span of a major league baseball: 7 pitches.',
  'When the University of Nebraska Cornhuskers play football at home, the stadium becomes the states third largest city.',
  'Cranberries are sorted for ripeness by bouncing them; a fully ripened cranberry can be dribbled like a basketball.',
  'In the marriage ceremony of the ancient Inca Indians of Peru, the couple was considered officially wed when they took off their sandals and handed them to each other.',
  'The longest word comprised of one row on the keyboard is: TYPEWRITER',
  'Conception occurs most in the month of December.',
  'Studies show that if a cat falls off the seventh floor of a building it has about thirty percent less chance of surviving than a cat that falls off the twentieth floor. It supposedly takes about eight floors for the cat to realize what is occurring, relax and correct itself.',
  'A pregnant goldfish is called a twit.',
  'It is illegal to eat oranges while bathing in California.',
  'The first song played on Armed Forces Radio during operation Desert Shield was "Rock the Casba" by the Clash.',
  'Mike Nesmiths (the guitarist of The Monkeys) mom invented White Out.',
  'There is a seven letter word in the English language that contains ten words without rearranging any of its letters, "therein": the, there, he, in, rein, her, here, ere, therein, herein.',
  'The verb "cleave" is the only English word with two synonyms which are antonyms of each other: adhere and separate.',
  'Most dust particles in your house are made from dead skin.',
  'A full-loaded supertanker traveling at normal speed takes at least 20 minutes to stop.',
  'There is a town in Newfoundland, Canada called Dildo.',
  'Firehouses have circular stairways originating from the old days when the engines were pulled by horses. The horses were stabled on the ground floor and figured out how to walk up straight staircases.',
  'The average North American will eat 35,000 cookies during their life span.',
  'A Boeing 747s wingspan is longer than the Wright brothers first flight.',
  'On average, people fear spiders more than they do death.',
  'You were born with 300 bones, but by the time you are an adult you will only have 206.',
  'There are more than 10 million bricks in the Empire State Building!',
  'Pamela Anderson Lee is Canadas Centennial Baby, being the first baby born on the centennial anniversary of Canadas independence.',
  'The highest per capita Jell-O comsumption in the US is Des Moines.',
  'Theres a systematic lull in conversation every 7 minutes.',
  'Average life span of a major league baseball: 7 pitches.',
  'The longest one-syllable word in the English language is "screeched."',
  'Ants closely resemble human manners: When they wake, they stretch & appear to yawn in a human manner before taking up the tasks of the day.',
  'The airplane Buddy Holly died in was the "American Pie." (Thus the name of the Don McLean song.)',
  'The male gypsy moth can "smell" the virgin female gypsy moth from 1.8 miles away.',
  'In Aspen Colorado, you can have a maximum income of $104,000 and still receive government subsidized housing.',
  'A cat has 32 muscles in each ear.',
  'A goldfish has a memory span of three seconds.',
  'Shakespeare invented the word assassination and bump.',
  'Between 25% and 33% of the population sneeze when exposed to light.',
  'Alfred Hitchcock didnt have a belly button. It was eliminated when he was sewn up after surgery.',
  'A crocodile cannot stick its tongue out.',
  'The Minneapolis phone book has 21 pages of Andersons.',
  'South Dakota is the only U.S state which shares no letters with the name of its capital',
  'Valentine Tapley from Pike County, Missouri grew chin whiskers attaining a length of twelve feet six inches from 1860 until his death 1910, protesting Abraham Lincolns election to the presidency.',
  'The microwave was invented after a researcher walked by a radar tube and a chocolate bar melted in his pocket.',
  'The expression to get fired comes from long ago Clans that wanted to get rid of unwanted people, so they would burn their houses instead of killing them, creating the term Got fired.',
  'All polar bears are left-handed.',
  'The shortest war in history was between Zanzibar and England in 1896. Zanzibar surrendered after 38 minutes.',
  'Over 1000 birds a year die from smashing into windows!',
  'The storage capacity of human brain exceeds 4 Terabytes.',
  'Ninety percent of all species that have become extinct have been birds.',
  'The Great Wall of China is the only man-made structure visible from space.',
  'Most lipstick contains fish scales!',
  'Odds of being killed by lightening? 1 in 2million/killed in a car crash? 1 in 5,000/killed by falling out of bed? 1 in 2million/killed in a plane crash? 1 in 25 million.',
  'The crack of a whip is actually a tiny sonic boom, since the tip breaks the sound barrier.',
  'Studies show that if a cat falls off the seventh floor of a building it has about thirty percent less chance of surviving than a cat that falls off the twentieth floor. It supposedly takes about eight floors for the cat to realize what is occurring, relax and correct itself.',
  'The Ramses brand condom is named after the great pharoh Ramses II who fathered over 160 children.',
  'You can sail all the way around the world at latitude 60 degrees south.',
  'Weatherman Willard Scott was the first original Ronald McDonald.',
  'Blueberry Jelly Bellies were created especially for Ronald Reagan.',
  'Right-handed people live, on average; nine years longer than left handed people.',
  'Each king in a deck of playing cards represents a great king from history. Spades - King David, Clubs - Alexander the Great, Hearts - Charlemagne, and Diamonds - Julius Caesar.',
  'You can sail all the way around the world at latitude 60 degrees south.',
  'The KGB is headquartered at No. 2 Felix Dzerzhinsky Square, Moscow',
  'Since 1978, 37 people have died by Vending Machines falling on them. 13 people are killed annually. All this while trying to shake merchandise out of them. 113 people have been injured.',
  'The the U.S. you dial 911. In Stockholm, Sweden you dial 90000',
  'Dolphins sleep with one eye open!',
  'Shakespeare is quoted 33,150 times in the Oxford English dictionary.',
  'The muzzle of a lion is like a fingerprint - no two lions have the same pattern of whiskers.',
  'The Boston University Bridge (on Commonwealth Avenue, Boston, Massachusetts) is the only place in the world where a boat can sail under a train driving under a car driving under an airplane.',
  'The San Francisco Cable cars are the only mobile National Monuments.',
  'Napoleons penis was sold to an American Urologist for $40,000.',
  'Elephants are the only animals that cant jump.',
  'The only two days of the year in which there are no professional sports games--MLB, NBA, NHL, or NFL--are the day before and the day after the Major League All-Star Game.',
  'Daffy Ducks middle name is "Dumas"',
  '166,875,000,000 pieces of mail are delivered each year in the US',
  'A Boeing 747s wingspan is longer than the Wright brothers first flight.',
  'The average talker sprays about 300 microscopic saliva droplets per minute, about 2.5 droplets per word.',
  '3.6 cans of Spam are consumed each second.',
  'A goldfish has a memory span of three seconds.',
  'In Disneys Fantasia, the Sorcerers name is "Yensid" (Disney backwards.)',
  'All 50 states are listed across the top of the Lincoln Memorial on the back of the $5 bill.',
  'Venus is the only planet that rotates clockwise.',
  'Tom Sawyer was the first novel written on a typewriter.',
  'Porcupines can float in water.',
  'The longest word comprised of one row on the keyboard is: TYPEWRITER',
  'There is a seven letter word in the English language that contains ten words without rearranging any of its letters, "therein": the, there, he, in, rein, her, here, ere, therein, herein.',
  'In every episode of Seinfeld there is a Superman somewhere.',
  'Mr. Rogers is an ordained minister.',
  'Lorne Greene had one of his nipples bitten off by an alligator while he was host of "Lorne Greenes Wild Kingdom."',
  'Dueling is legal in Paraguay as long as both parties are registered blood donors.',
  'The following sentence: A rough-coated, dough-faced, thoughtful ploughman strode through the streets of Scarborough; after falling into a slough, he coughed and hiccoughed. Contains the nine different pronunciations of "ough" in the English Language.',
  'Caesar salad has nothing to do with any of the Caesars. It was first concocted in a bar in Tijuana, Mexico, in the 1920s.',
  'During a severe windstorm or rainstorm the Empire State Building sways several feet to either side.',
  'The longest one-syllable word in the English language is "screeched."',
  'The average person spends 6 months of their life sitting at red lights.',
  'Sex burns 360 calories per hour.',
  'There are 1 million ants for every human in the world.',
  'Most toilets flush in E flat.',
  'To Ensure Promptness, one is expected to pay beyond the value of service – hence the later abbreviation: T.I.P.',
  'There are 1,792 steps in the Eiffel Tower',
  'THE MOST UNUSUAL CANNONBALL: On two occasions, Miss Rita Thunderbird remained inside the cannon despite a lot of gunpowder encouragement to do otherwise. She performed in a gold lamé bikini and on one of the two occasions (1977) Miss Thunderbird remained lodged in the cannon, while her bra was shot across the Thames River.',
  'The longest word in the English language, according to the Oxford English Dictionary, is: pneumonoultramicroscopicsilicovolcanoconiosis..',
  'The sperm of a mouse is actually longer than the sperm of an elephant.',
  'In eighteenth-century English gambling dens, there was an employee whose only job was to swallow the dice if there was a police raid.',
  'Any free-moving liquid in outer space will form itself into a sphere, because of its surface tension.',
  'The king of hearts is the only king without a mustache.',
  'Reindeer like to eat bananas.',
]
